language: cpp
compiler: clang
before_script:
- sudo apt install libboost-test-dev -y
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list.d/xenial.list
- sudo apt update
script:
- cd ./1_task
- mkdir build
- cd ./build
- cmake ../
- cmake --build . --target all
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uimelker:$BINTRAY_API_KEY "https://api.bintray.com/content/imelker/first_task/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
